### ISSUE TITLE
Cannot find parent error

### ISSUE THREAD

**Issue by merrickjeff** [TWExchangeSolutions/jira-precommit-hook#11]
Trying to commit against jira issue TW-2922, get an error:

"Cannot find parent from Epic TW-2897"

The issue I'm committing against is in the epic. The epic doesn't have a parent, unless I'm missing something.

**Comment by Stran6** [comment]
It should be working as intended because it is looking for an initiative from Epic TW-2897. A sub-task/story should eventually link to an initiative, otherwise it will fail.

**Comment by merrickjeff** [comment]
I asked Joe to verify the epic is linked to an initiative. He said it wasn't. Then he linked the epic to the correct initiative using "Linked Issues" and "Is depended on by"

Still get the same error. Is that not the right way to link an epic with an initiative?

**Comment by Stran6** [comment]
Instead of "is depended on by" it should be linked with "relates to". This is based on what we have seen with other issue links.

**Comment by merrickjeff** [comment]
Ok, That worked.Thanks
